FROM nginx:alpine
#usando uma imagem leve que já vem com um servidor nginx 

COPY mario-jump/usr/share/nginx/html/index.html
#copia os arquivos HTML do seu diretório local para o diretório de serviço do nginx dentro do contêiner.
#Nesse caso que estou usando o nginx é servido por padrão os arquivos do diretório /usr/share/nginx/html.

WORKDIR /app
#Organiza o sistema de arquivos dentro do contêiner
#eliminando a necesidade de especificar 
#caminhos absolutos para cada operação 

EXPOSE 443

RUN apt-get update && apt-get install 